global:
  amqp: amqp://guest:guest@amqp:5672/
  log-level: info
  instance-id: Local-Koinos

block_producer:
  algorithm: federated
  gossip-production: false

jsonrpc:
  listen: /tcp/8080

p2p:
  listen: /ip4/0.0.0.0/tcp/8888
